### ISSUE TITLE
Fixable compilation error: bluetooth/uuid.h

### ISSUE THREAD

**Issue by cryptax** [labapart/gattlib#1]
Hello,
When I compile your project, I get this error, because bluetooth/uuid.h is not found on my system.
[It seems this is an error of libbluetooth-dev package](https://github.com/jacklund/libgatt/issues/4) on Ubuntu 16 and similar devices.
See below.
I have found a workaround however.

```
$ make
Scanning dependencies of target gattlib
[  4%] Building C object CMakeFiles/gattlib.dir/bluez/attrib/att.c.o
/home/axelle/softs/gattlib/bluez/attrib/att.c:30:28: fatal error: bluetooth/uuid.h: No such file or directory
compilation terminated.
CMakeFiles/gattlib.dir/build.make:62: recipe for target 'CMakeFiles/gattlib.dir/bluez/attrib/att.c.o' failed
make[2]: *** [CMakeFiles/gattlib.dir/bluez/attrib/att.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/gattlib.dir/all' failed
make[1]: *** [CMakeFiles/gattlib.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

But actually, that missing `uuid.h` is `./bluez/lib/uuid.h`. So there are several ways to fix this: 

1. Modify all #include <bluetooth/uuid.h> into #include <uuid.h> 
2. Add a bluetooth directory and put a link to `./bluez/lib/uuid.h` and add . as directory to include.

**Comment by smerkousdavid** [comment]
I have also ran into this error. My solution was just to copy (as you have said) the uuid.h file to PREFIX/include. Can someone make a PR or fix the header to remove bluetooth? As @cryptax said the file is located at <GATTLIB_DIR>/bluez/lib/uuid.h.
