### ISSUE TITLE
can not scan (permission issue)

### ISSUE THREAD

**Issue by zewenhs** [labapart/gattlib#115]
It come error when I execute `ble_scan` command(with sudo)
` sudo ./examples/ble_scan/ble_scan`

> ERROR: Set scan parameters failed (are you root?).
> ERROR: Failed to scan.

How to avoid this error? thanks!

**Comment by oliviermartin** [comment]
Which version of Bluez are you using (`bluetoothctl --version`)? Recent version of Bluez do not require to launch `ble_scan` as root?

**Comment by zewenhs** [comment]
I have tried ubuntu 14.04 with bluez 5.44 and ubuntu 16.04 with 5.48, all have this NG result!

**Comment by oliviermartin** [comment]
How do you build `gattlib`? Can you also send me the build logs?
Do you confirm you have a bluetooth controller plugged on your PC and also the bluetooth adapter is enabled/power on?

**Comment by zewenhs** [comment]
I build `gattlib` follow the method mentioned in `README` file, the following command and log are on raspi 3B:
![image](https://user-images.githubusercontent.com/7780577/61096057-c2aaed00-a488-11e9-9026-17c96cecd0a4.png)

**Also I have checked `bluetoothctl` command:**

![image](https://user-images.githubusercontent.com/7780577/61095905-094c1780-a488-11e9-8239-95fade726396.png)

**cmake log:**
[cmake.log](https://github.com/labapart/gattlib/files/3384609/cmake.log)

**build log**
[build.log](https://github.com/labapart/gattlib/files/3384610/build.log)

I hvae a question, the bluez vesion is 5.50 in my raspi but gattlib say it's 5.23(show in the first picture which say `build gattlib for bluez v5.23`)?
![image](https://user-images.githubusercontent.com/7780577/61096576-b45dd080-a48a-11e9-8cb1-398d6fe3c991.png)

**Comment by oliviermartin** [comment]
How did you install bluez v5.50? Which Linux distribution are you using?

**Comment by zewenhs** [comment]
I install the official operating system which name is `Raspbian`, baseed on `debian`, and can be find [**here**](https://www.raspberrypi.org/downloads/)
![image](https://user-images.githubusercontent.com/7780577/61165497-edae4300-a553-11e9-9a3b-1b331238e13e.png)

And I follow this guide to install bluez 5.50: [Deploying BlueZ v5.50 on
Raspberry Pi 3 – Update](https://www.bluetooth.com/blog/bluez-on-raspberry-pi-update/)

**Comment by oliviermartin** [comment]
The build system gets confused between the two versions of Bluez installed on your system.

I have just added support to force building `gattlib` for a specific version. In your case:

```
rm -Rf *
cmake -DBLUEZ_VERSION=5.50 .. && make
```

**Comment by oliviermartin** [comment]
I will assume this new build option should fix your issue. Feel free to comment it or re-open this issue if you have still got an issue.
