### ISSUE TITLE
GATTLIB read ERROR

### ISSUE THREAD

**Issue by caferrick** [labapart/gattlib#143]
I was using the read_write example to extract data form Polar H7 Heart rate monitor. When i issue the following command I get this error. GDBus.Error:org.bluez.Error.NotPermitted: Read not permitted

 The command I am running is read_write.c example
  ./read_write 00:22:D0:A4:FC:2B read 0x2a37 
 I can run the discover with out any issues. This is the output from discover.c example   
 
  pi@raspberrypi:~/piProjects/btScan $ ./discover 00:22:D0:A4:FC:2B
service[0] start_handle:0d end_handle:0d uuid:0x1801
service[1] start_handle:21 end_handle:23 uuid:0x180a
service[2] start_handle:11 end_handle:11 uuid:0x180d
service[3] start_handle:00 end_handle:00 uuid:6217ff4b-fb31-1140-ad5a-a45545d7ecf3
characteristic[0] properties:20 value_handle:000d uuid:0x2a05
characteristic[1] properties:02 value_handle:0017 uuid:0x2a23
characteristic[2] properties:02 value_handle:0019 uuid:0x2a24
characteristic[3] properties:02 value_handle:001b uuid:0x2a25
characteristic[4] properties:02 value_handle:001f uuid:0x2a27
characteristic[5] properties:02 value_handle:001d uuid:0x2a26
characteristic[6] properties:02 value_handle:0023 uuid:0x2a29
characteristic[7] properties:02 value_handle:0021 uuid:0x2a28
characteristic[8] properties:02 value_handle:0014 uuid:0x2a38
characteristic[9] properties:10 value_handle:0011 uuid:0x2a37
characteristic[10] properties:02 value_handle:0029 uuid:6217ff4c-c8ec-b1fb-1380-3ad986708e2d
characteristic[11] properties:28 value_handle:002b uuid:6217ff4d-91bb-91d0-7e2a-7cd3bda8a1f3

 I installed the lastest vesion of BlueZ 5.52 running on Raspberry PI 4 

 What is very confusing I can connect and read data from the 
   gatttool -b 00:22:D0:A4:FC:2B --interactive
   and then issuing a write followed by a read.
I would appreciate any suggestion on how to get past this issue.

**Comment by oliviermartin** [comment]
Do you still have the issue? I am happy to re-open the bug if you still have.
