### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by Woody00h** [labapart/gattlib#147]
[ 63%] Generating documentation with Sphinx
/bin/sh: 1: SPHINX_EXECUTABLE-NOTFOUND: not found
make[2]: *** [docs/CMakeFiles/Sphinx.dir/build.make:58: docs/CMakeFiles/Sphinx] Error 127
make[1]: *** [CMakeFiles/Makefile2:185: docs/CMakeFiles/Sphinx.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

I install the Sphinx.
sudo apt-get install sphinxsearch

But it doesn't work. Build still fails.

**Comment by dumanovskis** [comment]
`sphinxsearch` is certainly not the right package, the project wants Python's Sphinx documentation generator. The right package might be `python-sphinx` or `python3-sphinx`.

You can also build without the documentation if you want, overriding the GATTLIB_BUILD_DOCS variable. Something like `cmake -DGATTLIB_BUILD_DOCS=NO .` when you invoke cmake.
