### ISSUE TITLE
Project setup question

### ISSUE THREAD

**Issue by pijuschanda** [labapart/gattlib#25]
I'm sorry to ask this question as a newbie, but I don't know how to proceed further.
My goal is to use the bluetooth stack Bluez5.23 on a raspberry 3 using a cross compilation setup based on eclipse running on ubuntu.
I don't want to build the gattlib from source, I just want to use the API provided with the library. I downloaded the .DEB package and extracted the gattlib.h and the libgattlib.so. I have set the include and library path of the compiler to find the files.
When I want to compile the examples e.g. discover, I need other API's for example gattlib_connect. This API is not defined in the gattlib.h.
I don't understand, why there are directories on the project site e.g. bluez. I see inside a file gattlib_connect.c which contains my missing function, but I thought, this gattlib_connect is part of the gattlib.so.

This is very confusing.
How shall I start?

Thanks

**Comment by oliviermartin** [comment]
The Gattlib v0.2 DEB package was quite old. I have just created a new package on the head of `gattlib`. For the new ARM package I released, Bluez DBus support is required with Bluez v5.40+.

So either you build the latest `gattlib` for your old version of Bluez or you upgrade your distribution on your rasberry 3. The Latest Debian stable `Stretch` support Bluez v5.43 and [run on Raspberry Pi 3](https://wiki.debian.org/RaspberryPi).

I close this issue for now. Feel free to re-open it.
