### ISSUE TITLE
NordicUart-example?

### ISSUE THREAD

**Issue by krimp** [labapart/gattlib#279]
Are there any plans to convert the NordicUart-example to the new interface?

**Comment by oliviermartin** [comment]
Hi @krimp, I have just ported the Nordic UART example: https://github.com/labapart/gattlib/pull/280
Do you mind to have a try and confirm me it works before I merge it? I have not tested it yet.

The code is quite similar to the previous code I tested.

**Comment by krimp** [comment]
Cloned and compiled the port-uart-example branch on a RPiZero2W.
It worked after changing m_connection to connection in line 100.

**Comment by oliviermartin** [comment]
Thanks a lot @krimp for your valuable feedback. I have taken your change in account in the PR and merged it!
