### ISSUE TITLE
Write handler gattlib_write_char_by_handle(...) isn't working

### ISSUE THREAD

**Issue by smerkousdavid** [labapart/gattlib#3]
When reading through even the read_write example. gattlib (ble) handler is set to a FIXME. I haven't been able to make a write without it failing with a non 0 status return code. I am not sure if I properly put the uint8_t buffer write. Will it error if the buffer size is over the MTU max. I am working with the Adafruit BLE module and the MTU is 32 bytes. Another thing i've noticed, is that the string to uuid method seems to not work. with standards like 6e400003-b5a3-f393-e0a9-e50e24dcca9e but non based hex codes work (like 2902). Some documentation would make this an amazing library for BLE devices.

**Comment by oliviermartin** [comment]
Hi @smerkousdavid , I have just implemented the 'write' in `example/read_write`: https://github.com/labapart/gattlib/commit/e11618bdeb4b4ce7a9994410b5e427d43c6dc246

I recently pushed some changes, it is likely to fix the UUID issue.
