### ISSUE TITLE
crash when reading some characteristics

### ISSUE THREAD

**Issue by ChristianKuehnel** [labapart/gattlib#4]
I was really happy to find a proper library for GATT, unfortunately I get a reproducible crash trying to read certain characteristics of my device:
`terminate called after throwing an instance of 'boost::python::error_already_set'`

a minimal code example is:
```
from gattlib import GATTRequester
req = GATTRequester(<some mac>)
value = req.read_by_handle(0x35)
```

It only happens with some characteristics while others work fine. So far I did not yet find a pattern when is succeeds or fails.

When reading the same value with gatttool it works fine:
```
$ gatttool -b <mac> --char-read -a 0x35
Characteristic value/descriptor: aa bb cc dd ee ff 99 88 77 66 00 00 00 00 00 00 
```

**Comment by oliviermartin** [comment]
Christian, I think you raised an issue in the wrong project. This `gattlib` project is mainly to write a C GATT client while you are looking at the `gattlib` python project - probably this project: <https://bitbucket.org/OscarAcena/pygattlib>.
