### ISSUE TITLE
UUID type incompatibility

### ISSUE THREAD

**Issue by hunterakins** [labapart/gattlib#51]
I am modifying the nordic_uart.c example to connect to a custom profile I made.
I have a macro for the string:
#define DS18B20_UUID "efd11001-9d13-6fff-a455-00d658aac524"
gattlib_string_to_uuid converts the string to a UUID with type UUID32.
However, gattlib_discover_characteristics finds its handle, but its associated uuid has a UUID16 representation. 
When I print the UUID strings, I get for the gattlib_discover_characteristic uuid:
0x10011-9d13-6fff-a455-00d658aac5240
instead of as 
efd11001-9d13-6fff-a455-00d658aac524.

Also, I don't know why there is a zero on the end.

I am confused about how to go forward. It's not clear to me if there exists a way to compare uuid16 and uuid32...(perhaps by simply looking at the last 16 bits of the uuid32 ?). If that is the case, then I can add a case to the gattlib_uuid_compare function. Or perhaps I need to find a way to write my string that yields a UUID16 type uuid?

**Comment by oliviermartin** [comment]
I cannot duplicate your issue:

```
#include <stdio.h>

#include "gattlib.h"

#define DS18B20_UUID "efd11001-9d13-6fff-a455-00d658aac524"

int main(int argc, char *argv[]) {
    uuid_t test_uuid;
    char uuid_str[100];

    int ret = gattlib_string_to_uuid(DS18B20_UUID, strlen(DS18B20_UUID) + 1, &test_uuid);
    if (ret) {
        fprintf(stderr, "Fail to convert characteristic TX to UUID.\n");
        return 1;
    }

    ret = gattlib_uuid_to_string(&test_uuid, uuid_str, sizeof(uuid_str));
    if (ret) {
        fprintf(stderr, "Fail to convert characteristic TX to String.\n");
        return 1;
    } else {
        printf("UUID:%s\n", uuid_str);
    }

    return 0;
}
```

The result is: `UUID:efd11001-9d13-6fff-a455-00d658aac524`

I am using `DBus gattlib for Bluez v5.45`.

Feel free to re-open the issue if the issue persists but please give your Bluez version and some code to duplicate the issue.
