### ISSUE TITLE
Make throws error when building GATTLIB

### ISSUE THREAD

**Issue by PTmv** [labapart/gattlib#67]
When trying to build gattlib for Raspbian GNU/Linux v 9 (stretch) for Raspberry Pi 3 on Ubuntu v 16.04.2, having installed BlueZ v 5.49 and Linaro cross-compiler v 4.9, I am getting the following error on make:

$ make
 [ 1%] Building C object bluez/CMakeFiles/gattlib.dir/gattlib_adapter.c.o
 In file included from /home/ptomov/Toolchains/gcc-linaro-4.9-2015.05-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.9.3/include-fixed/syslimits.h:7:0,
 from /home/ptomov/Toolchains/gcc-linaro-4.9-2015.05-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.9.3/include-fixed/limits.h:34,
 from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:11,
 from /usr/include/glib-2.0/glib/gtypes.h:32,
 from /usr/include/glib-2.0/glib/galloca.h:32,
 from /usr/include/glib-2.0/glib.h:30,
 from /home/ptomov/Downloads/GATTLIB/gattlib-master/bluez/gattlib_internal.h:27,
 from /home/ptomov/Downloads/GATTLIB/gattlib-master/bluez/gattlib_adapter.c:1:
 /home/ptomov/Toolchains/gcc-linaro-4.9-2015.05-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.9.3/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h> /* recurse down to the real one */
 ^
 compilation terminated.
 bluez/CMakeFiles/gattlib.dir/build.make:62: recipe for target 'bluez/CMakeFiles/gattlib.dir/gattlib_adapter.c.o' failed
 make[2]: *** [bluez/CMakeFiles/gattlib.dir/gattlib_adapter.c.o] Error 1
 CMakeFiles/Makefile2:85: recipe for target 'bluez/CMakeFiles/gattlib.dir/all' failed
 make[1]: *** [bluez/CMakeFiles/gattlib.dir/all] Error 2
 Makefile:149: recipe for target 'all' failed
 make: *** [all] Error 2

I have installed in my Ubuntu system libc:i386 with version 2.23-0ubuntu10. I have also applied the fix in: 
https://github.com/labapart/gattlib/issues/66. The problem still persists.
 Please advise me how to solve this problem. Thanks.

**Comment by oliviermartin** [comment]
Thanks @PTmv for reporting this issue.
We now have travis-ci that builds the different versions of gattlib. And there is no compilation issue. So I am assuming this issue is fixed. If it is not, feel free to open a new issue.
