### ISSUE TITLE
gattlib.h needs better documentation

### ISSUE THREAD

**Issue by platypro** [labapart/gattlib#70]
While using gattlib, it was not immediately obvious while using gattlib_read_char_by_uuid that I needed to set len to be the size of the buffer before passing it in. I don't know if this is apparent on all backends or just the dbus one, but in any case it should have been documented somehow. 
I understand that the example shows this detail rather implicitly, but it kept me busy for a good few hours. Personally, I would like if gattlib.h was more comprehensive. Currently it isn't very well documented.

**Comment by oliviermartin** [comment]
I have finally finished to document all [`gattlib.h`](https://github.com/labapart/gattlib/blob/master/include/gattlib.h). Thanks for having create the issue. It pushed me to get it right :+1:
