### ISSUE TITLE
changes to notifictaion.c

### ISSUE THREAD

**Issue by YikeStone** [labapart/gattlib#71]
The below lines should added to notification.c after g_main_loop_unref(loop).

g_main_loop_quit(loop);
gattlib_notification_stop(connection, &g_battery_level_uuid);
gattlib_disconnect(connection);

For clean exit and avoiding segmentation fault.
Otherwise there are issues on reconnecting immediately.

**Comment by hpo14** [comment]
maybe you can make a PR.
