### ISSUE TITLE
gattlib_read_char_by_uuid returns '-1' for battery service

### ISSUE THREAD

**Issue by onderweg** [labapart/gattlib#73]
I'm able to successfully read characteristic values from my devices with `gattlib_read_char_by_uuid`.
(Bluez 5.43)

However, when reading battery level (char uuid `00002a19-0000-1000-8000-00805f9b34fb`), `gattlib_read_char_by_uuid` returns `-1`.

With `gatttool` i'm able to read this characteristic:

```
char-read-uuid 00002a19-0000-1000-8000-00805f9b34fb
```

returns:

```
handle: 0x0003   value: 64
```

The only difference I noted is that the battery char is in a different service than the characteristics I can successfully read with gattlib. Furthermore, battery service is not included in services returned by `gattlib_discover_primary`, while it is listed in gatttool `primary` command response.

I have this issue with multiple types of devices (tested with thermometer and tracking tag)

Any ideas?

**Comment by oliviermartin** [comment]
@onderweg Try the latest version, I have just pushed a commit https://github.com/labapart/gattlib/commit/10af2f197101d4ec13f4693ccaf102939222f450 that fixes reading battery level with Buez v5.48+.
Maybe it also fix your issue.

I close your ticket for now. Feel free to re-open it if you can duplicate the issue.
