### ISSUE TITLE
on_handle_characteristic_property_change is passing connection on notification_handler

### ISSUE THREAD

**Issue by lluisdiaz** [labapart/gattlib#76]
On gattlib.c 
``connection->notification_handler(&uuid, data, data_length, user_data) ``

... should be ...
``connection->notification_handler(&uuid, data, data_length, connection->notification_user_data) ``

This is causing a segmentation fault if any parameter is passed to user data on 
`gattlib_register_notification`

**Comment by oliviermartin** [comment]
Fix in https://github.com/labapart/gattlib/commit/1402183eddf8b6417a9e409ce83c5460a663abe1
