### ISSUE TITLE
Failed to start notification (example application)

### ISSUE THREAD

**Issue by PhilippFinke** [labapart/gattlib#84]
I'm using gattlib under Fedora 29 (Workstation Edition) using bluez 5.50. Additonally I'm using a battery level sample application of Zephyr running on an nrf52840_pca10056 development board. With this setup I'm not able to start notifications by using the notification example application. I always get a NotSupported error.

**Comment by oliviermartin** [comment]
Have you got a simple gattlib example I can used to quickly duplicate your test. I have a `nrf52840_pca10056` at home I can use to duplicate it.

**Comment by PhilippFinke** [comment]
Thanks for the fast reply. Here's the Zephyr sample I used. You can flash it with nrfjprog (remove .txt before).
[peripheral_hr.hex.txt](https://github.com/labapart/gattlib/files/2836662/peripheral_hr.hex.txt)

**Comment by PhilippFinke** [comment]
Hey Olivier,

did you already found time to work on this issue?

**Comment by oliviermartin** [comment]
My latest change should fix your issue: https://github.com/labapart/gattlib/commit/ff07ac89f198f7688b8b7f72d971a7ed3a57d04a
